Repository opt-nc/yamlfixer, pull requests merged in 2022-03, with the labels that each got.

#12 Nicer README
  README.md
Labels: documentation

#15 add yaml files example
  examples/bad.yml
  examples/good.yml
Labels: documentation

#21 Docker install howto
  README.md
Labels: documentation, delivery

#20 Add Katacoda scenario
  README.md
Labels: documentation

#22 Remove docker section as people have to mont volumes
  README.md
Labels: documentation

#26 Badge with current pypi released version
  README.md
Labels: documentation

#37 🚀 One liners : pipe into jq
  README.md
Labels: documentation

#42 Fix windows install step
  README.md
Labels: documentation

#44 Linux and windows emojis onte install part
  README.md
Labels: documentation

#55 Better contact url
  README.md
Labels: documentation, communication

#56 Tips & tricks section
  README.md
Labels: documentation

#57 More about radtadidi
  AUTHORS.md
Labels: documentation, communication

#59 Activate CodeQL alerts
  .github/workflows/codeql-analysis.yml
Labels: security, maintenance

#66 asciinema demo on README
  README.md
Labels: documentation

#61 Communication : Video
  README.md
Labels: communication

#68 Add related single-purposed tools section
  README.md
Labels: documentation

#79 Add blog DEV.to post
  README.md
Labels: documentation, communication
